// DO NOT EDIT. Generated by "pika:routes" plugin of Pika.
// This file should be checked into version control.

export const views = [
  {
    path: "/:user/:repo",
    component: () => import("./routes/_user/_repo.vue"),
    props: true,
    meta: {
      shadow: import.meta.env.SSR ? () => import("./routes/_user/_repo.js") : null
    }
  },
  {
    path: "/:user",
    component: () => import("./routes/_user/index.vue"),
    props: true
  },
  {
    path: "/about",
    component: () => import("./routes/about.vue"),
    props: true
  },
  {
    path: "/",
    component: () => import("./routes/index.vue"),
    props: true
  }
];

export const endpoints = [
  {
    pathname: "/:user/:repo",
    load: () => import("./routes/_user/_repo.js")
  }
];
